## 1. Preprocessing Datasets

In [1]:
import pandas as pd

# Adjusted column names for the dataset
news_columns = [
    "NewsID",        # Unique identifier for the article
    "Category",      # Main category of the article
    "Subcategory",   # Subcategory of the article
    "Title",         # Title of the article
    "Abstract",      # Short description of the article
    "URL",            # URL of the article
    "Label 1",
    "Label 2"
]

# Load the datasets
news_file = r"C:\Users\Naineek\Desktop\New\Sabudh DS Internship\Module Coursework\Recommender Systems\Group Assignment\MINDlarge_train\news.tsv"
behaviors_file = r"C:\Users\Naineek\Desktop\New\Sabudh DS Internship\Module Coursework\Recommender Systems\Group Assignment\MINDlarge_train\behaviors.tsv"

# Load news data
news = pd.read_csv(news_file, sep="\t", header=None, names=news_columns)
print("Loaded News Data: ", news.shape)

# Load behaviors data
behaviors = pd.read_csv(behaviors_file, sep="\t", header=None, names=["ImpressionID", "UserID", "Time", "History", "Impressions"])
print("Loaded Behaviors Data: ", behaviors.shape)

Loaded News Data:  (101527, 8)
Loaded Behaviors Data:  (2232748, 5)

In [21]:
news.head()

,NewsID,Category,Subcategory,Title,Abstract,URL,Label 1,Label 2
0,N88753,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N45436,news,newsscienceandtechnology,Walmart Slashes Prices on Last-Generation iPads,Apple's new iPad releases bring big deals on l...,https://assets.msn.com/labs/mind/AABmf2I.html,"[{""Label"": ""IPad"", ""Type"": ""J"", ""WikidataId"": ...","[{""Label"": ""IPad"", ""Type"": ""J"", ""WikidataId"": ..."
2,N23144,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
3,N86255,health,medical,Dispose of unwanted prescription drugs during ...,NaN,https://assets.msn.com/labs/mind/AAISxPN.html,"[{""Label"": ""Drug Enforcement Administration"", ...",[]
4,N93187,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."

In [22]:
print(news.info())  # Check for null values
print(news.isnull().sum())  # Summarize missing data
print(news['Category'].unique())  # List unique categories

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101527 entries, 0 to 101526
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   NewsID       101527 non-null  object
 1   Category     101527 non-null  object
 2   Subcategory  101527 non-null  object
 3   Title        101527 non-null  object
 4   Abstract     96112 non-null   object
 5   URL          101527 non-null  object
 6   Label 1      101524 non-null  object
 7   Label 2      101521 non-null  object
dtypes: object(8)
memory usage: 6.2+ MB
None
NewsID            0
Category          0
Subcategory       0
Title             0
Abstract       5415
URL               0
Label 1           3
Label 2           6
dtype: int64
['lifestyle' 'news' 'health' 'sports' 'weather' 'entertainment'
 'foodanddrink' 'autos' 'travel' 'video' 'finance' 'tv' 'movies' 'music'
 'kids' 'middleeast' 'games' 'northamerica']

In [2]:
news.drop(["Label 1", "Label 2"], axis = 1, inplace = True) # Drop unnecessary columns
news.dropna(inplace = True) # Drop rows with null values

In [4]:
print("Updated News Data: ", news.shape)
print(news.isnull().sum())  # Summarize missing data
news.head()

Updated News Data:  (96112, 6)
NewsID         0
Category       0
Subcategory    0
Title          0
Abstract       0
URL            0
dtype: int64

,NewsID,Category,Subcategory,Title,Abstract,URL
0,N88753,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html
1,N45436,news,newsscienceandtechnology,Walmart Slashes Prices on Last-Generation iPads,Apple's new iPad releases bring big deals on l...,https://assets.msn.com/labs/mind/AABmf2I.html
2,N23144,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html
4,N93187,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html
5,N75236,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html

In [37]:
behaviors.head()

,ImpressionID,UserID,Time,History,Impressions
0,1,U87243,11/10/2019 11:30:54 AM,N8668 N39081 N65259 N79529 N73408 N43615 N2937...,N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...
1,2,U598644,11/12/2019 1:45:29 PM,N56056 N8726 N70353 N67998 N83823 N111108 N107...,N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...
2,3,U532401,11/13/2019 11:23:03 AM,N128643 N87446 N122948 N9375 N82348 N129412 N5...,N103852-0 N53474-0 N127836-0 N47925-1
3,4,U593596,11/12/2019 12:24:09 PM,N31043 N39592 N4104 N8223 N114581 N92747 N1207...,N38902-0 N76434-0 N71593-0 N100073-0 N108736-0...
4,5,U239687,11/14/2019 8:03:01 PM,N65250 N122359 N71723 N53796 N41663 N41484 N11...,N76209-0 N48841-0 N67937-0 N62235-0 N6307-0 N3...

In [38]:
print(behaviors.isnull().sum())  # Summarize missing data

ImpressionID        0
UserID              0
Time                0
History         46065
Impressions         0
dtype: int64

In [3]:
behaviors.dropna(inplace = True) # Drop rows with null values

In [6]:
print("Updated behaviors Data: ", behaviors.shape)
print(behaviors.isnull().sum())  # Summarize missing data
behaviors.head()

Updated behaviors Data:  (2186683, 5)
ImpressionID    0
UserID          0
Time            0
History         0
Impressions     0
dtype: int64

,ImpressionID,UserID,Time,History,Impressions
0,1,U87243,11/10/2019 11:30:54 AM,N8668 N39081 N65259 N79529 N73408 N43615 N2937...,N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...
1,2,U598644,11/12/2019 1:45:29 PM,N56056 N8726 N70353 N67998 N83823 N111108 N107...,N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...
2,3,U532401,11/13/2019 11:23:03 AM,N128643 N87446 N122948 N9375 N82348 N129412 N5...,N103852-0 N53474-0 N127836-0 N47925-1
3,4,U593596,11/12/2019 12:24:09 PM,N31043 N39592 N4104 N8223 N114581 N92747 N1207...,N38902-0 N76434-0 N71593-0 N100073-0 N108736-0...
4,5,U239687,11/14/2019 8:03:01 PM,N65250 N122359 N71723 N53796 N41663 N41484 N11...,N76209-0 N48841-0 N67937-0 N62235-0 N6307-0 N3...

## 2. Preprocess Clickstream Data

#### Prepare the user clickstream data for the profiler bot.

In [4]:
# Split impressions into clicked and not clicked articles
def process_impressions(row):
    impressions = row.split()
    clicked = [imp.split("-")[0] for imp in impressions if imp.split("-")[1] == "1"]
    return clicked

# Process user click history and impressions
behaviors['ClickedArticles'] = behaviors['Impressions'].apply(process_impressions)
behaviors['HistoryList'] = behaviors['History'].str.split(" ")

# Drop unnecessary columns
behaviors = behaviors.drop(columns=['Impressions', 'History'])

# Display processed data
print("Processed Behaviors Data: \n", behaviors.head())

Processed Behaviors Data:
    ImpressionID   UserID                    Time  \
0             1   U87243  11/10/2019 11:30:54 AM
1             2  U598644   11/12/2019 1:45:29 PM
2             3  U532401  11/13/2019 11:23:03 AM
3             4  U593596  11/12/2019 12:24:09 PM
4             5  U239687   11/14/2019 8:03:01 PM

                    ClickedArticles  \
0  [N94157, N78699, N71090, N31174]
1                  [N25587, N36266]
2                          [N47925]
3                         [N114935]
4                          [N86258]

                                         HistoryList
0  [N8668, N39081, N65259, N79529, N73408, N43615...
1  [N56056, N8726, N70353, N67998, N83823, N11110...
2  [N128643, N87446, N122948, N9375, N82348, N129...
3  [N31043, N39592, N4104, N8223, N114581, N92747...
4  [N65250, N122359, N71723, N53796, N41663, N414...

## 3. Article Recommender Bot

#### Recommend articles based on categories or user profiles.

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Combine Title and Abstract to create article content
news['Content'] = news['Title'] + " " + news['Abstract']

# Compute TF-IDF vectors for article content
vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = vectorizer.fit_transform(news['Content'])


# Recommend articles based on cosine similarity or handle cold start
def recommend_articles(user_history, top_n=10):
    if not user_history:  # Cold start: No user history available
        return news.sample(n=top_n)[['NewsID', 'Title', 'Category', 'Abstract']]  # TOP N recommendation
    
    # Find indices of articles in user history
    history_indices = [news[news['NewsID'] == nid].index[0] for nid in user_history if nid in news['NewsID'].values]
    if not history_indices:  # Handle case where history doesn't match any articles
        return news.sample(n=top_n)[['NewsID', 'Title', 'Category', 'Abstract']]
    
    # Calculate similarities
    history_tfidf = tfidf_matrix[history_indices]
    similarities = cosine_similarity(history_tfidf, tfidf_matrix)
    scores = similarities.sum(axis=0)
    top_indices = scores.argsort()[-top_n:][::-1]
    return news.iloc[top_indices][['NewsID', 'Title', 'Category', 'Abstract']]

# Example: Recommend for a user
user_history_example = []  # Replace with actual user history ["N39081", "N114581"] OR set user_history_example = []  when No user profile is available
recommendations = recommend_articles(user_history_example)
print("Recommendations: ", recommendations)

Recommendations:          NewsID                                              Title Category  \
31388   N17398  Sinkhole opens, swallows part of city bus duri...     news
18418   N92012  US helicopters seen still patrolling Syria by ...    video
52159   N62336  Anibal Sanchez had classy response after losin...   sports
68270   N69328  Patriots Still Smiling Despite Loss To Ravens:...   sports
12553   N21073            Cub Tracks and the epoch of incredulity   sports
27421   N96667  Jags place WR Marqise Lee on IR, promote CB Ta...   sports
97743  N119570  Report: NFL will no longer provide list of per...   sports
27084   N41465  How many SEC teams will reach the NCAA Tournam...   sports
14905   N89937  Ohio State national championship QB Cardale Jo...   sports
84494   N57877  Multiple Patriots Players Comment On Josh Gord...   sports

                                                Abstract
31388  The front of a city bus went up in the air aft...
18418  CNN's Nick Paton Wash reports from Syria where...
52159  Anibal Sanchez had an extremely classy respons...
68270  FOXBORO Mass. -- Morale was high New England P...
12553  Getting older to get better, the next phase of...
27421  The Jags didn't make any trades before the dea...
97743  Additionally, a number of teams have contact K...
27084  Who will push Kentucky in the SEC this season?...
14905  The XFL draft kicked off Tuesday with a name v...
84494  https://www.dailymotion.com/embed/video/x ns u...

## 4. User Profiler Bot

#### Update user preferences based on clickstream.

In [22]:
import tkinter as tk
from time import time

# Initialize Clickstream DataFrame
clickstream_data = pd.DataFrame(columns=[
    'UserId', 'SessionID', 'ArticleID', 'Served Rank', 'Click', 'Time Spent (seconds)'
])

# Interaction Tracker Variables
current_user = 1
current_session = 1
active_article = None
start_time = None
accessed_articles = []  # Track the sequence of accessed articles

# Function to start tracking a user's interaction with an article
def start_article_tracking(article_id):
    """Start tracking a user's interaction with an article."""
    global active_article, start_time
    if active_article:
        print(f"Already tracking Article ID {active_article}. Please stop tracking first.")
        return

    # Set the article being tracked and start the timer
    active_article = article_id
    start_time = time()

    print(f"Started tracking Article ID {article_id}")

# Function to stop tracking interaction and update the clickstream data
def stop_article_tracking(article_id, clicked):
    """Stop tracking interaction and update clickstream data."""
    global active_article, start_time, clickstream_data

    if not active_article:
        print("No article is currently being tracked.")
        return

    # Calculate the time spent if the article was clicked
    elapsed_time = time() - start_time if clicked else 0

    # Assign served rank based on the sequence of accessed articles
    served_rank = len(accessed_articles) + 1  # Rank is based on order of access

    # Add the new interaction to the clickstream data
    clickstream_data = pd.concat([
        clickstream_data,
        pd.DataFrame([{
            'UserId': current_user,
            'SessionID': current_session,
            'ArticleID': article_id,
            'Served Rank': served_rank,  # Assign sequential rank based on access order
            'Click': 'Yes' if clicked else 'No',
            'Time Spent (seconds)': elapsed_time
        }])
    ], ignore_index=True)

    # Add the article to the list of accessed articles
    accessed_articles.append(article_id)

    print(f"Stopped tracking Article ID {article_id}. Clicked: {clicked}, Time Spent: {elapsed_time:.2f}s")
    active_article = None
    start_time = None

# Function to analyze clickstream data and extract user interests
def analyze_clickstream():
    """Analyze clickstream data and extract user interests."""
    global clickstream_data

    if clickstream_data.empty:
        print("No interactions to analyze.")
        return

    # Assuming 'news' DataFrame is predefined elsewhere, merge it with clickstream_data
    enriched_data = clickstream_data.merge(news, left_on='ArticleID', right_on='NewsID', how='left')
    category_summary = (
        enriched_data.groupby('Category')['Time Spent (seconds)']
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    print("\nUser Interests (Top Categories):")
    print(category_summary)

    # Save clickstream data for further use
    clickstream_data.to_csv("clickstream_data.csv", index=False)
    print("\nClickstream data saved to 'clickstream_data.csv'")

    return category_summary

# Function to create the GUI for interacting with articles and recording user clickstream
def create_gui(user_history_example):
    """Create a GUI for interacting with articles and recording user clickstream."""
    global news, current_user, current_session

    # Create the main Tkinter window first
    root = tk.Tk()
    root.title("User Interaction Tracker")

    # Create a list of users for selection (User IDs from 1 to 5)
    users = [1, 2, 3, 4, 5]
    user_var = tk.IntVar(value=1)  # Default to User 1

    # Handler for changing the user selection
    def user_changed(*args):
        """Handler to update the current user and reset session."""
        global current_user, current_session, accessed_articles
        current_user = user_var.get()
        current_session = 1  # Reset session for each user
        accessed_articles = []  # Reset accessed articles for each user

    user_menu = tk.OptionMenu(root, user_var, *users)
    user_menu.pack(pady=10)
    user_var.trace_add("write", user_changed)

    # Function to increment session ID for the current user
    def increment_session():
        """Increment session ID for the current user."""
        global current_session
        current_session += 1

    # Simulated function to recommend articles based on user history
    recommendations = recommend_articles(user_history_example)

    # Display instructions
    tk.Label(root, text="Click on an article to interact.").pack(pady=10)

    # Display the recommended articles and serve them with sequential ranks (1 to 10)
    for idx, row in recommendations.iterrows():
        article_id = row['NewsID']
        article_title = row['Title']

        # Create a button for each article that tracks interactions
        button = tk.Button(
            root, text=f"{article_title} (ID: {article_id})", fg="blue",
            command=lambda aid=article_id: start_article_tracking(aid)
        )
        button.pack(pady=5)

    # Buttons to stop tracking with or without a click
    tk.Button(root, text="Stop Tracking (No Click)", command=lambda: stop_article_tracking(active_article, clicked=False)).pack(pady=10)
    tk.Button(root, text="Stop Tracking (Clicked)", command=lambda: stop_article_tracking(active_article, clicked=True)).pack(pady=10)
    
    # Button to analyze the clickstream data
    tk.Button(root, text="Analyze Data", command=analyze_clickstream).pack(pady=10)

    # Function to save the data and exit the application
    def exit_application():
        clickstream_data.to_csv("clickstream_data.csv", index=False)
        print("Clickstream data saved to 'clickstream_data.csv'")
        root.destroy()

    tk.Button(root, text="Exit", command=exit_application).pack(pady=10)

    # Start the GUI main loop
    root.mainloop()

# Example Launch: Cold Start User History (Use actual data in place of [])
create_gui(user_history_example=[])

Started tracking Article ID N106216
Stopped tracking Article ID N106216. Clicked: False, Time Spent: 0.00s
Started tracking Article ID N113247
Stopped tracking Article ID N113247. Clicked: False, Time Spent: 0.00s
Started tracking Article ID N82549
Stopped tracking Article ID N82549. Clicked: True, Time Spent: 13.41s
Started tracking Article ID N19234
Stopped tracking Article ID N19234. Clicked: True, Time Spent: 2.98s
Started tracking Article ID N81931
Stopped tracking Article ID N81931. Clicked: True, Time Spent: 5.70s
Started tracking Article ID N113247
Stopped tracking Article ID N113247. Clicked: True, Time Spent: 1.13s
Started tracking Article ID N106216
Stopped tracking Article ID N106216. Clicked: True, Time Spent: 4.86s
Clickstream data saved to 'clickstream_data.csv'

## Key Points Summary of the Code

#### Data Loading and Preprocessing:
#### - News articles (news.tsv) and user behavior (behaviors.tsv) datasets are loaded and processed.
#### - Splits the Impressions column into clicked articles (ClickedArticles), and processes History into a list (HistoryList) for easier access.
#### - Merges news and behaviors DataFrames for further analysis.
####
#### TF-IDF Vectorization and Article Recommendation:
#### - Combines article titles and abstracts to create textual features.
#### - Converts them into numerical vectors using Tfidf Vectorizer.
#### - Defines a recommendation function that suggests articles to users based on their history using cosine similarity between article vectors.
#### - If no user history is available (cold start), it uses TOP N Recommendation technique.
####
#### Clickstream Data Collection:
#### - Initializes a clickstream_data DataFrame to track user interactions.
#### - Tracks article interactions by starting and stopping article tracking with timestamps and calculates time spent on each article.
#### - Assigns a "Served Rank" to each article interaction based on the order in which articles are accessed by the user.
####
#### Clickstream Analysis:
#### - Analyzes the clickstream data by merging it with the news dataset to identify user interests (e.g., categories of articles with the most time spent).
#### - Saves the clickstream data to a CSV file (clickstream_data.csv) for further use.
####
#### User Interaction via GUI (Tkinter):
#### - A Tkinter GUI is created where users can interact with a list of recommended articles.
#### - Users can start tracking an article, stop tracking (with or without clicking), and view the total time spent on each article.
#### - Articles are recommended and displayed with sequential ranks (from 1 to 10).
#### - Buttons to analyze clickstream data and save it to a CSV file are included in the GUI.
#### 
#### Functionality for Data Saving and Exiting:
#### - Data can be saved by clicking the "Exit" button in the GUI, which stores the clickstream_data DataFrame to a CSV file.